apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-store-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/10weeksofcloudops
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-store-pvc
  namespace: democloudops
spec:
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-configmap
  namespace: democloudops
data:
  REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/10weeksofcloudops
  REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
  REGISTRY_HTTP_TLS_KEY: /certs/domain.key
  REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
  REGISTRY_AUTH: htpasswd
  REGISTRY_HTTP_ADDR: 0.0.0.0:5000

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: democloudops
data:
  htpasswd: |
    dGVzdHVzZXI6JDJ5JDA1JDdaaFpwOVRZSkNKWkRoYXNaT1Fsek9hRWpsNGVPYUVEQXNJaC9vUWJw
    V0NlRW1CSjF3L1dTCgo=
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-cert-secret
  namespace: democloudops
data:
  domain.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZNVENDQXhtZ0F3SUJBZ0lVYnZVMW5RY0Vh
    eCtqTmQyRWluZmdyN1gyb3Rvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF3d1Ba
    RzlqYTJWeUxYSmxaMmx6ZEhKNU1CNFhEVEl6TURrd05ERTRNREkwTWxvWApEVEkwTURrd016RTRN
    REkwTWxvd0dqRVlNQllHQTFVRUF3d1BaRzlqYTJWeUxYSmxaMmx6ZEhKNU1JSUNJakFOCkJna3Fo
    a2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQTFRYWpRSHhjcHRzQmlXODk5eDdhSmRTdWk3
    c3kKZ2I0ZTRHVTFYaFNOa2pnTC9lbytjQmI0d2ZtZkdHN29uekNRRXdMYkJIY2RQUzdWem02MUV1
    dnJOUXdLamgwQwoya2k1UWZQb1RKZE5oLzludG5PdG5TOVA2VWNaMUVlQVRBNzlDenp1V3RIK2My
    WHhEbFRhaGYyZUd5V0g4ZEFlCkxNQ3RKMTFwbVR3Nk5waWNrdi9qSDFIam5BV2QxNVVPaFgrMnZ4
    Q1V2UzFJRUdENUZ5blNna01hNUNWbUxTYk4KN1JNYkRyNWtaREdoMHNiRDFPd29qNzhIUVVkQkla
    KzY3ZEVHcFB3YWh2VVRZNUFOZE1oL2wrRENtc1BBL3BEMgo3Z3dkaFQwMy9VSTE3Ry85VTdCa1ZV
    M1FtbVZIOUcwRVJxdzFmWm0yMWFXZExUeE10VkdEeitTS0pEOWNXNkpZCnh5bDVYTHhrTC9Eb3Jo
    WEFvRnYrWC9qMkExWXdJQWozMGdVK2ZXQ0hEZ3AzUzFURHBxNkcvZzhrT1FBNXN1eWsKcTRuUk9F
    MmQ5c0JZNEJrdEYweG1TSnRMZjN6RGFxSjJ0d3Y0c2wxWjZhMlVaaTcwZmZyMk0vVlkyeG1FdkZn
    bwo4aDZvM3UyTVdtdlFXbHVjTytQWVYyZUMrYTJuNk13MDhxR1N2TzBVcXFkQjFlRmxsRVpTdFRP
    VFJTTHlYbkV1CjVGc0J3Q1VYemp5bThvWHpCZncweEdJQnN0czU3N1FQNTNFQXJtL1NwRHNtS0Ix
    L1NXQ001bm0rY0tpVHk0Uk4KZHF5VVpmRUdrMzIvQkZMSi9PTlhkakU1ZTRrNVZnVU82WWgzTlNV
    UmZkRzg0cXl2VTBiMVlyNHowUXRLTDNhQQpma2sxVS81bkYwUlg5enNDQXdFQUFhTnZNRzB3SFFZ
    RFZSME9CQllFRk9ucFFEV0RHRmFPYWY1bUJjaEdaa2RsCjNmbWJNQjhHQTFVZEl3UVlNQmFBRk9u
    cFFEV0RHRmFPYWY1bUJjaEdaa2RsM2ZtYk1BOEdBMVVkRXdFQi93UUYKTUFNQkFmOHdHZ1lEVlIw
    UkJCTXdFWUlQWkc5amEyVnlMWEpsWjJsemRISjVNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElDQVFE
    Q1VYZ1JVOGc2N2xmWCtYeDVnTFY2ZzlvR1lyaFRta0lVUXlFRXV5STBGRzVxSHRtaE14TEpOSnhz
    CmFPcWhRUWVHWnVIK2QxaTNqZldOK0xnUzF3OXkrSkcwZjhCcTYzU1NkRlJFcWRQYitHWHVDckk4
    dUNzSXhrSEwKYWFHdUNEdnE5SDNxSlJraC9qMmNRL29RM0VaNVlNbHNSU3liZmN4VER2b0wxdStl
    eEYxV2RIcjVNWGIwYWpVNQpScW9La0I5cWtEMXlZVlhudWtMeHJNWlYxZ2FvZmdEN05yV0grVFkv
    UGpMaHBINGgzaHpHT0VHMDlmK3oxZ04zCnBMaFZ5d21FaE9hckRuMTR4d05JekR6aEE4eHkxZHNH
    NFQrY1FhbEg4a3MvZkFVVTBpSnpmUFV2TmxzT2ZFTVQKdGlkVlZ0Q0kvbU43dzBnUDlzbmIxMmhq
    OU9aMlFnOGdiRnB6cllOSE9hbDFmN21XZlNFT1I0a1AyZUJvbGJYUQpPbk10MHVKQXB0L3oybThF
    Ulo4SzVUYmdmYmRCTzNIUEZ0S2NTbk5ZNlBKYWNFMVhudFZQVXQ5U1hKdEpWUkRUClhvSGxOdlhB
    aVNpa2RVc1VLUXRDcndLdzAwVFc5OVkxOHF2UmpjS0EyRVRFc29vYTZMcXlldjhiMVN3SDVDZ1oK
    WTJFN2FXWTk5M0RpKzE0L0lEV09Jak9QMGlCTk16VDRNc2lCelYra3d1S21DM2RsSCtqM2l2RGJ0
    VWQ3QW42MgpvVE0vZnM2Y2RSd3I5Q3FRaEFsRG9YNEd6RVFsbFVPZnViWTNmaWdUd3llT1gwVmpC
    Ty9nQkR4QUNnNU85VksrCk1aNlJqbzR1UmhiK1NEek01S1NQNW55Rnk0QTNleEV4Q1A5cGlPVm9F
    Nno1UzFOdFJBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

  domain.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQ1N3d2dna29BZ0VBQW9JQ0FRRFZCcU5BZkZ5bTJ3R0oKYnozM0h0b2wxSzZMdXpLQnZoN2da
    VFZlRkkyU09Bdjk2ajV3RnZqQitaOFlidWlmTUpBVEF0c0VkeDA5THRYTwpiclVTNitzMURBcU9I
    UUxhU0xsQjgraE1sMDJILzJlMmM2MmRMMC9wUnhuVVI0Qk1EdjBMUE81YTBmNXpaZkVPClZOcUYv
    WjRiSllmeDBCNHN3SzBuWFdtWlBEbzJtSnlTLytNZlVlT2NCWjNYbFE2RmY3YS9FSlM5TFVnUVlQ
    a1gKS2RLQ1F4cmtKV1l0SnMzdEV4c092bVJrTWFIU3hzUFU3Q2lQdndkQlIwRWhuN3J0MFFhay9C
    cUc5Uk5qa0ExMAp5SCtYNE1LYXc4RCtrUGJ1REIyRlBUZjlRalhzYi8xVHNHUlZUZENhWlVmMGJR
    UkdyRFY5bWJiVnBaMHRQRXkxClVZUFA1SW9rUDF4Ym9sakhLWGxjdkdRdjhPaXVGY0NnVy81ZitQ
    WURWakFnQ1BmU0JUNTlZSWNPQ25kTFZNT20Kcm9iK0R5UTVBRG15N0tTcmlkRTRUWjMyd0ZqZ0dT
    MFhUR1pJbTB0L2ZNTnFvbmEzQy9peVhWbnByWlJtTHZSOQordll6OVZqYkdZUzhXQ2p5SHFqZTdZ
    eGFhOUJhVzV3NzQ5aFhaNEw1cmFmb3pEVHlvWks4N1JTcXAwSFY0V1dVClJsSzFNNU5GSXZKZWNT
    N2tXd0hBSlJmT1BLYnloZk1GL0RURVlnR3kyem52dEEvbmNRQ3ViOUtrT3lZb0hYOUoKWUl6bWVi
    NXdxSlBMaEUxMnJKUmw4UWFUZmI4RVVzbjg0MWQyTVRsN2lUbFdCUTdwaUhjMUpSRjkwYnppcks5
    VApSdlZpdmpQUkMwb3Zkb0IrU1RWVC9tY1hSRmYzT3dJREFRQUJBb0lDQUV1cnYvSDRPekZLT3BH
    SFlvdVYrZ2ZXCk5PcU41TE1SeGdZUDdaVXQxOXhJN0htVjYvZ0ZNUGcybzcwYUtLZmpxRW9ZaVpS
    Y2U1WndQS0xIMEtxWUEwVWsKc2RzcGt3blhLM2V5SEtLWVhJSWl4OFNYOHVRVEdsL1RVZW1HUEp6
    SDlqczN1Yk9wUktuWlhIZXF6TFVzRWkyeQpkMGYrbGJsditCSXpySDh5VmJ0dkdxOWRGbURaeGZC
    MlRrdDJOMkpVcTZYVFRnS2xReVFPVG0xYi9kc24yeldQCjAydldqTy9hQ1pLREwwWW9HME8wTjN3
    N0oyMW9manRDQkhEZFBKbWQxcTVrbjBleFp1SEhHZ0NSK0VFTEpoV3oKMDZxWjlCMDdVSUV6N2Qr
    WTFXN1htVFZSUTFMS0FYL1cybWlKRVN2Sm9IYXRVN1V3ejFSeVJ3MWhsMkVSM2IrOApDM0hBdWRB
    VWlzZ3ZiUDQ0K3FHN29zWHZDNTI0MFVTTDNScFdYU3JaNDdQdWk5Si9PaHFDa3RFdjZXeHdUSG9u
    CnlIWUN2RjVIMyt0SVpmeHMrakNCdVk3ejl6cElqSGt4QzhNb2laOGdUSUwvSW9tZ1ZtZVVjZExD
    eVNYVGlqMmMKSnpuZnVBbnl1UVBoQ093YUY0cXprVyt0aXVaNVBMVmlzOURsbk9RNGxpMEk3SDBZ
    Z1IrRUE1dEdhZU9xT0R1MQoyTXR3U2dYMUJqY29vdHREdEZYVldtd2ZIM2J3aVEvTy9aUVhIOUx2
    aW9EaXJWbVBZS3BlMXlSWC8xY1g1R1BGCllGbXFLTmJGY1I0NmdCK3JYRDBjODhDblE0aXFNNUZT
    NDVvS1dJVER2bzZ4QzJQa3gvczRIeTlQV1RDMXNmOHUKODJRd0FQRDRFRVg0TTNrdTZUV0JBb0lC
    QVFEOWJGUGRzdXF3aEFTbzJQOG9HSTZQQXNKRnNXUW5ZbUduNHJFTQpTb1Nwa3hmQ1pDZ1FYcFFr
    ZFVMbDlONmxVMDY0eGhRZjVZaEY4Ymd6eG94ZW8wZXdSMm9qUGZMV0dNbU15UHh6CllWdUMxNnJF
    elFvdmhPd01kTm9iNFQ2cEMvUkNuM3JHT0wrTlpGVVpQb25pUSs5eTFiSFBYVzdaTWd6dDE3TjkK
    L0tRTTl4QXdJcWJNS3FraGNJbnlTYU1WM1dnZk1STUZxZGtRM0U5TWsrTzN6ZDI5bjEybkZCTUtD
    RVRRQmtoagpsakY0MzI3RTlPM3MrSlAvejRxbTE3cXdvYkw2WStLb2w0am1oWk9uVE5EU3pyNWkr
    WDU1YlVqT1l3aDFqbnFpCkplKzl2MXZwdFRCeDFMM1Q5TS9RSGRJd3BKNTVpWlNvSHRmK2N0RkZG
    ckkyMlg4OUFvSUJBUURYTVNkNitjY3oKaEQ5VThEVjRJZjdvVjNORXU3QktIREdpckFZVjdqWm9X
    bngzUVZOTEVaSVowSXc0aC9WQmJUY2V4NUlDTlMrSQozUUNnRXRUNHhmeGtOa0IwTjlaamVXdmtU
    N2V1Z01hVHU5TTJUK1pTbWdqaC85TW1ZblNLNzZOaDFzTXFTUjZSClBESkdMUEhCL0o0cHZlSGpS
    bTdCcURWcnlVNkp0clFLWUg3VGlaME1qUGhEQUh3Tjg5aTJlYzBHV0QzRnVDem4KMWNlWmFyYUxB
    cXplVVMyWUNReW91NnRjS2t0cldoc2xCaVlDcnBtcGpwZlE5VFZTWXpETzk5Y1Z4Z0JSdmdNVQor
    RytoaWxIQ3ZIUEI0aDFZelZLMkdlSzdIT2N5Zno0WmdVZGd1ZG5HNFVnMTNYSGl4MkNJUUZJTmx0
    OEpGemJSCjN6WVlPSE4wT0RmWEFvSUJBUURQZXhsT3NXVWtEM0loSzBmNzg5OERoeWEzR0h6L0li
    VUNWcjdOYVZVajRLSGIKTFZULzBlOUh5aGx6Vy8vTksxK1FOOXZTSVlKb2dYWm1MWEJQS3k5T1M2
    bkNJTDNvTzNNSUtLVkhjYllTY2JBRwpZRGl1bncwRFJjZ3NlMFZwOGJlUnREQTRpYzJLWFZLdTBG
    empPdXVZQVEwSzBWd254cXAvTDlKc202TlVXaEtPCjFrL3BhQ1FBbExyYit4M2lrTnJtYnE4OE84
    clQyd3V4am9NcHdRcUNiUytuMHUramp4R0hueDAxSzRwbGc4aVUKeUZMamFNRUM5MUIxT0xwSVVw
    ck9GV2xFem92dTcvM3JReURVOXg4NHVUdXEvcVpWRXcraDczekh0SGVMeWxmZQpCOUlaNEN0cWxV
    eHUvM3RQQi9nWFdXUzBJRXlHcmtwWFhqV2FZb2VoQW9JQkFDZnhxdGRyNStzTElFcGU4RDNsCmFa
    Q3RNdXRPUDVIeUc5Q0xSL0hvTHRjOS9KNlNWS2k1a1RvVGVRUEJVT2dkSXI4bTRsWmdrdnMvc3E4
    RDc5NWgKdWRETU5UaWRhTUU4TjZmQW1HTGU2bjFmdnZ2MDV0YnNXcnZBcGV3WkdITDF1b2tkdVVw
    dkdpcHhWdytwcGhLUgpGcmErMVdBL29hMTIwTHU2T1ViYzBCeWcvc203WUppRXpreDVtWTFwZHcr
    Z0drdVVNNXN3N2J6MjlMN29qUXZPCnFsSDJGWldFRUlKOW0zaFhMWHEyMWhVUVNCdjFWdmFmVGxU
    dVAwQ1V3dW1ZSGFlZ0FrMHFEUjVtWXlwRUo1c1QKS2hXU0tFcGtpbmJjNVRaQVRqWVVZbTJQanJW
    SXFrRDliazc1VlB0NGNOVzV3c0ZkQVBlS0JKWCtiZWNmQzJkRwpUQzhDZ2dFQU5hUmdnOUpvTEc1
    ZEx2Ym1TSkxsUndDNlhRMnJMNmRzZDVSRkgzZWFwYkVZeVI5ZTg3VWJGNWhDCndCYk5kblNwSWZx
    eHYybTY2SjZwMkpXZWZSbDd0dVl2MEU0Uzhqc0NBSWpWWTQzUUZUdnFYaFdDZmtxYmZhYysKbnp3
    Q3VTQWE4N0huZ1ZtYm9FNFdyd3EyZ3lPY3BwTElQZkpZRkVGU2x6bUQyOE05NjhMUm1zWXRrNlB3
    SmJCWgpzbXgydWhOOW16YzVTV1J3NXlGcHZyQ0Q5RTNkWm8xZ0U0NXZPYS8yNmNBUkVPMHIrYTl3
    WXpQMFNCZmVBSFFxCmtzVmtLZDYyY2RvRmcvSDJvU3h1N1U3bEpTNWQ3WGE1YzhsT3FwNU1YUXU0
    aEpVTm9uMzZxVFo0QlFMUWt2VmMKSzZhZTV1TmM0eGlyMGlTcnBLR3BWMEl4N1hhelRRPT0KLS0t
    LS1FTkQgUFJJVkFURSBLRVktLS0tLQo=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-deployment
  namespace: democloudops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: docker-registry-zone
                operator: In
                values:
                - a
                - b
                - c
      volumes:
      - name: data-store
        persistentVolumeClaim:
          claimName: docker-store-pvc
      - name: registry-secret
        secret:
          secretName: docker-registry-secret
      - name: registry-cert-secret
        secret:
          secretName: docker-cert-secret
      initContainers:
      - name: alpine-init-container
        image: alpine:latest
        command:
        - 'sh'
        - '-c'
        - 'mkdir -p /var/lib/10weeksofcloudops'
      containers:
      - name: registry-cloudops
        image: registry:2.8.2
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 30
        envFrom:
        - configMapRef:
            name: registry-configmap
        volumeMounts:
        - name: data-store
          mountPath: /var/lib/10weeksofcloudops
        - name: registry-secret
          mountPath: /auth
        - name: registry-cert-secret
          mountPath: /certs
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "2Gi"
        ports:
        - containerPort: 5000



---

apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: democloudops
spec:
  type: LoadBalancer
  selector:
    app: docker-registry
  ports:
  - port: 5000
    targetPort: 5000

---
