apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-configmap
  namespace: democloudops
data:
  REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/10weeksofcloudops
  REGISTRY_HTTP_TLS_CERTIFICATE: /certs/tls.crt
  REGISTRY_HTTP_TLS_KEY: /certs/tls.key
  REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
  REGISTRY_AUTH: htpasswd
  REGISTRY_HTTP_ADDR: 0.0.0.0:5000

