# Store sensitive information in Kubernetes Secrets, such as authentication credentials for the Docker registry.
# Utilize a ConfigMap to manage configuration settings for the Docker registry deployment.
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-configmap
  namespace: democloudops
data:
  REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/10weeksofcloudops
  REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
  REGISTRY_HTTP_TLS_KEY: /certs/domain.key
  REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
  REGISTRY_AUTH: htpasswd

# docs
# https://docs.docker.com/registry/deploying/#run-an-externally-accessible-registry


# These examples assume the following:

# Your registry URL is https://myregistry.domain.com/.
# Your DNS, routing, and firewall settings allow access to the registry's host on port 443.
# You have already obtained a certificate from a certificate authority (CA).
