apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-store-pvc
  namespace: democloudops
spec:
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-store-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/10weeksofcloudops
  storageClassName: ""

# Configure a Persistent Volume (PV) to store data for the application.
# The PV should request at least 50Gi of storage space.
# Ensure the data stored in the PV survives pod restarts.
